### ISSUE TITLE
Issue on page /06_concurrency/01_threading.html

### ISSUE THREAD

**Issue by kathirmeyyappan** [UCHI-DB/rust-guide#13]
`for i in 1..10` instead of `for i in 1..=10` for code that generates 10 lines. Same for main thread loop (`..= 5`).

**Comment by suhailrehman** [comment]
Thanks! Fixed in [5716a08](https://github.com/UCHI-DB/rust-guide/commit/5716a08e97051d9e8943fda592fa5aa06c0040f9)
